### ISSUE TITLE
Re-Balance Trophies, update HoS Trophies

### ISSUE THREAD

**Issue by Chickenudoom** [Lknechtli/BetterCombatEvolved#10]
Some trophies are too weak while other's are just too strong. Also HoS trophies haven't been touched yet, we need to put them on-par with BCEv trophies.

**Comment by BardBlue** [comment]
Well, it's not too bad if some trophies are a little weaker than others if they come from weaker monsters. Should the first trophy from the noonwraith be just as good as a fiend trophy? There's definitely a balance between variety and rewarding a particularly hard monster with a particularly good trophy. I can't be too specific, since I don't have too many trophies (and also unfortunately sold some before I got this mod), except why is foglet -450 instead of -500? :P Maybe up its gold bonus to 15% too, 5% basically has no effect.

Edit: Was thinking of succubus bonus being 5%, foglet already at 25%. Another thought: a few trophies should benefit alchemy somehow (max toxicity, potion length) if that's possible.

**Comment by BardBlue** [comment]
So not sure about the new trophies. They all seem so... complicated now. Lots of random -3% critical chance bonuses and the like. IMO, they should all have 4 modifiers, max, and affect everything by at least 5%. And I actually wouldn't mind if they had bigger bonuses and drawbacks, like -30% sign intensity but +80% one particular sign intensity (so +50% for that sign), though that does complicate balance more. 

Still way better than vanilla trophies, but I actually almost find looting a trophy LESS exciting with the new patch than the older ones you had. Things with like 5+ minor effects are just less interesting to me than something with 2 or 3 bigger effects.

**Comment by Lknechtli** [comment]
I have to agree with Bard, they trophies should force you to change the way you play
things like -50% stam regeneration/+50 stam, etc

**Comment by BardBlue** [comment]
Yeah, something like that sounds great. Random ideas (numbers are just guesses, but the point is they should have a hearty effect on your character instead of this -3% crit chance stuff):

-25% vitality but +20% attack power (another trophy could do the reverse)

+25% critical hit damage, -10% attack power

25% faster adrenaline generation, -25% stamina generation

+75% X sign, -25% sign intensity (five different trophies right there)

+50% gold drop, -25% experience from kills

+100% burning and poison resist, -25% armor (for a fire/poison bomb heavy playstyle)

+20% chance to freeze, -50% burning resist, -15% armor (if you can do negative resists)

+10% chance for insta kills, -50% armor

There has to be some way to affect alchemy with items besides boring stuff like chance for more herbs. I feel like alchemy seriously got shafted in the loot department.
